global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'changemind-api'
    static_configs:
      - targets: ['changemind-api:8080']
        labels:
          service: api

  - job_name: 'changemind-gateway'
    static_configs:
      - targets: ['changemind-gateway:8080']
        labels:
          service: gateway

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
