// <auto-generated />
using System;
using ChangeMind.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChangeMind.Infrastructure.Migrations
{
    [DbContext(typeof(ChangeMindDbContext))]
    [Migration("20260404124923_FixExerciseSeedDataWithStaticIds")]
    partial class FixExerciseSeedDataWithStaticIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChangeMind.Domain.Entities.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Coaches_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Coaches_IsActive");

                    b.ToTable("Coaches", (string)null);
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.CoachUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UnassignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_CoachUsers_IsActive");

                    b.HasIndex("UserId");

                    b.HasIndex("CoachId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_CoachUsers_CoachId_UserId");

                    b.ToTable("CoachUsers", (string)null);
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("MovementName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MovementName")
                        .HasDatabaseName("IX_Exercises_MovementName");

                    b.HasIndex("MuscleGroup")
                        .HasDatabaseName("IX_Exercises_MuscleGroup");

                    b.ToTable("Exercises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010001"),
                            MovementName = "Barbell Bench Press",
                            MuscleGroup = "Chest"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010002"),
                            MovementName = "Incline Dumbbell Press",
                            MuscleGroup = "Chest"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010003"),
                            MovementName = "Decline Bench Press",
                            MuscleGroup = "Chest"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010004"),
                            MovementName = "Cable Flyes",
                            MuscleGroup = "Chest"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010005"),
                            MovementName = "Machine Chest Press",
                            MuscleGroup = "Chest"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010006"),
                            MovementName = "Smith Machine Press",
                            MuscleGroup = "Chest"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000020001"),
                            MovementName = "Pull-ups",
                            MuscleGroup = "Back"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000020002"),
                            MovementName = "Lat Pulldown",
                            MuscleGroup = "Back"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000020003"),
                            MovementName = "Bent-over Barbell Row",
                            MuscleGroup = "Back"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000020004"),
                            MovementName = "T-Bar Row",
                            MuscleGroup = "Back"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000020005"),
                            MovementName = "Seal Row",
                            MuscleGroup = "Back"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000020006"),
                            MovementName = "Chest-Supported Row",
                            MuscleGroup = "Back"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000030001"),
                            MovementName = "Overhead Press",
                            MuscleGroup = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000030002"),
                            MovementName = "Lateral Raise",
                            MuscleGroup = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000030003"),
                            MovementName = "Machine Shoulder Press",
                            MuscleGroup = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000030004"),
                            MovementName = "Reverse Pec Deck",
                            MuscleGroup = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000030005"),
                            MovementName = "Arnold Press",
                            MuscleGroup = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000040001"),
                            MovementName = "Barbell Curl",
                            MuscleGroup = "Biceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000040002"),
                            MovementName = "Dumbbell Curl",
                            MuscleGroup = "Biceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000040003"),
                            MovementName = "Cable Curl",
                            MuscleGroup = "Biceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000040004"),
                            MovementName = "Preacher Curl",
                            MuscleGroup = "Biceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000050001"),
                            MovementName = "Tricep Dips",
                            MuscleGroup = "Triceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000050002"),
                            MovementName = "Rope Pushdown",
                            MuscleGroup = "Triceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000050003"),
                            MovementName = "Skull Crusher",
                            MuscleGroup = "Triceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000050004"),
                            MovementName = "Overhead Extension",
                            MuscleGroup = "Triceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000060001"),
                            MovementName = "Barbell Curl (Reverse)",
                            MuscleGroup = "Forearms"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000060002"),
                            MovementName = "Wrist Curls",
                            MuscleGroup = "Forearms"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000070001"),
                            MovementName = "Barbell Back Squat",
                            MuscleGroup = "Legs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000070002"),
                            MovementName = "Leg Press",
                            MuscleGroup = "Legs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000070003"),
                            MovementName = "Leg Extension",
                            MuscleGroup = "Legs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000070004"),
                            MovementName = "Hamstring Curl",
                            MuscleGroup = "Legs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000070005"),
                            MovementName = "Smith Machine Squat",
                            MuscleGroup = "Legs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000070006"),
                            MovementName = "Hack Squat",
                            MuscleGroup = "Legs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000070007"),
                            MovementName = "Leg Sled",
                            MuscleGroup = "Legs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000080001"),
                            MovementName = "Front Squat",
                            MuscleGroup = "Quadriceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000080002"),
                            MovementName = "Sissy Squat",
                            MuscleGroup = "Quadriceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000090001"),
                            MovementName = "Romanian Deadlift",
                            MuscleGroup = "Hamstrings"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000090002"),
                            MovementName = "Good Morning",
                            MuscleGroup = "Hamstrings"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000100001"),
                            MovementName = "Hip Thrust",
                            MuscleGroup = "Glutes"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000100002"),
                            MovementName = "Bulgarian Split Squat",
                            MuscleGroup = "Glutes"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000100003"),
                            MovementName = "Glute-Focused Leg Press",
                            MuscleGroup = "Glutes"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000110001"),
                            MovementName = "Calf Raise",
                            MuscleGroup = "Calves"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000110002"),
                            MovementName = "Machine Calf Raise",
                            MuscleGroup = "Calves"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000120001"),
                            MovementName = "Cable Crunch",
                            MuscleGroup = "Abs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000120002"),
                            MovementName = "Machine Crunch",
                            MuscleGroup = "Abs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000120003"),
                            MovementName = "Ab Wheel Rollout",
                            MuscleGroup = "Abs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000130001"),
                            MovementName = "Cable Woodchop",
                            MuscleGroup = "Obliques"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000130002"),
                            MovementName = "Landmine Rotation",
                            MuscleGroup = "Obliques"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000140001"),
                            MovementName = "Deadlift",
                            MuscleGroup = "LowerBack"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000140002"),
                            MovementName = "Hyperextension",
                            MuscleGroup = "LowerBack"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000150001"),
                            MovementName = "Barbell Shrugs",
                            MuscleGroup = "Traps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000150002"),
                            MovementName = "Dumbbell Shrugs",
                            MuscleGroup = "Traps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000160001"),
                            MovementName = "Wide Grip Lat Pulldown",
                            MuscleGroup = "LatissimusDorsi"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000160002"),
                            MovementName = "Underhand Lat Pulldown",
                            MuscleGroup = "LatissimusDorsi"
                        });
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Packages_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Packages_Name");

                    b.ToTable("Packages", (string)null);
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PackageId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Payments_CreatedAt");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("IX_Payments_PackageId");

                    b.HasIndex("PackageId1");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Payments_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Payments_UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.TrainingProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DailyProgramJson")
                        .HasColumnType("json");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Difficulty")
                        .HasColumnType("text");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CoachId")
                        .HasDatabaseName("IX_TrainingPrograms_CoachId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_TrainingPrograms_IsActive");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_TrainingPrograms_UserId");

                    b.ToTable("TrainingPrograms", (string)null);
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FitnessGoal")
                        .HasColumnType("text");

                    b.Property<string>("FitnessLevel")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<decimal?>("Height")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Users_IsActive");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.UserPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MeasurementsJson")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ViewType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserPhotos_UserId");

                    b.HasIndex("ViewType")
                        .HasDatabaseName("IX_UserPhotos_ViewType");

                    b.ToTable("UserPhotos", (string)null);
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.WaitingUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsWaitingForAssignment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsWaitingForAssignment")
                        .HasDatabaseName("IX_WaitingUsers_IsWaitingForAssignment");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_WaitingUsers_UserId");

                    b.ToTable("WaitingUsers", (string)null);
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.CoachUser", b =>
                {
                    b.HasOne("ChangeMind.Domain.Entities.Coach", "Coach")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChangeMind.Domain.Entities.User", "User")
                        .WithMany("CoachRelationships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.Payment", b =>
                {
                    b.HasOne("ChangeMind.Domain.Entities.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChangeMind.Domain.Entities.Package", "Package")
                        .WithMany("Payments")
                        .HasForeignKey("PackageId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChangeMind.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChangeMind.Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.TrainingProgram", b =>
                {
                    b.HasOne("ChangeMind.Domain.Entities.Coach", "CreatedBy")
                        .WithMany("CreatedPrograms")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChangeMind.Domain.Entities.User", "AssignedTo")
                        .WithMany("AssignedPrograms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.UserPhoto", b =>
                {
                    b.HasOne("ChangeMind.Domain.Entities.User", "User")
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.WaitingUser", b =>
                {
                    b.HasOne("ChangeMind.Domain.Entities.User", "User")
                        .WithOne("WaitingUserRecord")
                        .HasForeignKey("ChangeMind.Domain.Entities.WaitingUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.Coach", b =>
                {
                    b.Navigation("AssignedUsers");

                    b.Navigation("CreatedPrograms");
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.Package", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedPrograms");

                    b.Navigation("CoachRelationships");

                    b.Navigation("Payments");

                    b.Navigation("Photos");

                    b.Navigation("WaitingUserRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
