// <auto-generated />
using System;
using ChangeMind.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChangeMind.Infrastructure.Migrations
{
    [DbContext(typeof(ChangeMindDbContext))]
    [Migration("20260505205700_AddIsCompletedProfileToUser")]
    partial class AddIsCompletedProfileToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChangeMind.Domain.Entities.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Coaches_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Coaches_IsActive");

                    b.ToTable("Coaches", (string)null);
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.CoachUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UnassignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_CoachUsers_IsActive");

                    b.HasIndex("UserId");

                    b.HasIndex("CoachId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_CoachUsers_CoachId_UserId");

                    b.ToTable("CoachUsers", (string)null);
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("MovementName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Exercises_IsActive");

                    b.HasIndex("MovementName")
                        .HasDatabaseName("IX_Exercises_Name");

                    b.HasIndex("MuscleGroup")
                        .HasDatabaseName("IX_Exercises_MuscleGroup");

                    b.ToTable("Exercises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Düz bankta bar ile yapılan bu baskı hareketi, pektoral kasların tamamını hedef alır. Omuz genişliğinden biraz daha geniş tutuş ile bar göğse indirilip itilir; göğüs, ön omuz ve triseps birlikte çalışır.",
                            IsActive = true,
                            MovementName = "Barbell Bench Press",
                            MuscleGroup = "Chest"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Eğimli bankta dumbbell ile yapılan bu egzersiz, üst göğüs (klavikular pektoral) kaslarını özellikle aktive eder. Her iki kol bağımsız hareket ettiğinden kas dengesizliklerini gidermeye yardımcı olur.",
                            IsActive = true,
                            MovementName = "Incline Dumbbell Press",
                            MuscleGroup = "Chest"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Negatif eğimli bankta gerçekleştirilen bu hareket, alt göğüs kaslarını ve sternal pektoral lifleri yoğun biçimde çalıştırır. Bar, normal bench'e göre daha aşağı bir noktaya temas eder.",
                            IsActive = true,
                            MovementName = "Decline Bench Press",
                            MuscleGroup = "Chest"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kablo makinesiyle yapılan bu izolasyon hareketi, göğüs kaslarını en geniş hareket açısında çalıştırır. Sürekli gerilim sağlaması nedeniyle kas bağlantıları üzerinde etkili bir germe ve sıkıştırma hissi yaratır.",
                            IsActive = true,
                            MovementName = "Cable Flyes",
                            MuscleGroup = "Chest"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sabit bir yörüngede hareket eden makine baskısı, özellikle başlangıç seviyesindeki kullanıcılar için güvenli bir göğüs egzersizidir. Yardımcı kasları devre dışı bırakarak pektorallere odaklanmayı kolaylaştırır.",
                            IsActive = true,
                            MovementName = "Machine Chest Press",
                            MuscleGroup = "Chest"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Smith makinesi üzerinde yapılan bu baskı hareketi, barın sabit ray üzerinde hareket etmesiyle denge gerektirmeksizin ağır yük kaldırmaya olanak tanır. Göğüs kaslarını kontrollü biçimde çalıştırır.",
                            IsActive = true,
                            MovementName = "Smith Machine Press",
                            MuscleGroup = "Chest"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000020001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vücut ağırlığıyla yapılan bu egzersiz, latissimus dorsi, rombus ve biceps kaslarını eş zamanlı çalıştırır. Avuç içleri dışa bakacak şekilde tutunularak çene barın üzerine çıkarılır; üst sırt gelişiminin temel hareketlerinden biridir.",
                            IsActive = true,
                            MovementName = "Pull-ups",
                            MuscleGroup = "Back"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000020002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kablo makinesiyle geniş bir bar kullanılarak yapılan bu hareket, latissimus dorsi kaslarını etkili biçimde hedef alır. Bar omuz altına kadar çekilir ve sırt kaslarının tam sıkışması hissedilir.",
                            IsActive = true,
                            MovementName = "Lat Pulldown",
                            MuscleGroup = "Back"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000020003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Öne eğik pozisyonda bar ile yapılan bu çekiş hareketi, orta ve üst sırt kaslarını derinlemesine çalıştırır. Gövde 45 derece açıyla sabit tutulurken bar göbek bölgesine doğru çekilir.",
                            IsActive = true,
                            MovementName = "Bent-over Barbell Row",
                            MuscleGroup = "Back"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000020004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "T-bar aparatı veya landmine kullanılarak yapılan bu sırt egzersizi, kalın ve hacimli sırt kasları geliştirmek için etkilidir. Barın sabit ucunun yere çakılı olması, hareketi daha stabil hale getirir.",
                            IsActive = true,
                            MovementName = "T-Bar Row",
                            MuscleGroup = "Back"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000020005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yatay bankta yüz aşağı uzanarak yapılan bu sırt egzersizi, alt trapez ve rombus kaslarını izole eder. Gövde tamamen desteklendiğinden momentum kullanımı minimize edilir ve saf kas kuvveti ölçülür.",
                            IsActive = true,
                            MovementName = "Seal Row",
                            MuscleGroup = "Back"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000020006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Göğüs destekli sırt çekişi, gövde salınımını ortadan kaldırarak orta sırt kaslarını izole şekilde çalıştırır. Eğimli banka yaslanılarak yapılan bu hareket, bel üzerindeki yükü azaltır.",
                            IsActive = true,
                            MovementName = "Chest-Supported Row",
                            MuscleGroup = "Back"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000030001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Omuzların üzerine bar veya dumbbell iterek yapılan bu bileşik egzersiz, ön ve orta deltoid ile trisepsi birlikte çalıştırır. Ayakta veya oturarak uygulanabilir; omuz gelişiminin temel hareketlerinden sayılır.",
                            IsActive = true,
                            MovementName = "Overhead Press",
                            MuscleGroup = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000030002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kolların yanlara doğru kaldırıldığı bu izolasyon hareketi, orta deltoid kasını doğrudan hedef alır. Hafif ağırlıkla kontrollü biçimde yapılması, omuz ekleminin korunması açısından kritiktir.",
                            IsActive = true,
                            MovementName = "Lateral Raise",
                            MuscleGroup = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000030003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Makine üzerinde yapılan omuz baskısı, sabit yörüngesiyle özellikle başlangıç ve rehabilitasyon aşamasındaki sporcular için güvenli bir seçenektir. Deltoid kaslarını dengeli şekilde çalıştırır.",
                            IsActive = true,
                            MovementName = "Machine Shoulder Press",
                            MuscleGroup = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000030004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pec deck makinesi üzerinde ters yönde gerçekleştirilen bu hareket, arka deltoid ve rhomboid kaslarını izole eder. Postür bozukluklarını düzeltmeye yardımcı olan bu egzersiz üst sırt sağlığı için önemlidir.",
                            IsActive = true,
                            MovementName = "Reverse Pec Deck",
                            MuscleGroup = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000030005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Arnold Schwarzenegger tarafından popülerleştirilen bu hareket, ön ve orta deltoidi geniş bir açıda çalıştırır. Dumbbell'lar avuç içleri içe bakacak şekilde başlar ve baskı sırasında dışa döner.",
                            IsActive = true,
                            MovementName = "Arnold Press",
                            MuscleGroup = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000040001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Düz bar ile yapılan bu klasik biceps egzersizi, hem kısa hem uzun başı eş zamanlı aktive eder. Dirsekler sabit tutularak bar omuz hizasına kadar kaldırılır; biceps gelişiminin temel hareketidir.",
                            IsActive = true,
                            MovementName = "Barbell Curl",
                            MuscleGroup = "Biceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000040002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Her kol bağımsız çalıştığından kas dengesizliklerini gidermeye yardımcı olan dumbbell curl, supinasyon hareketi ile biceps'in tüm liflerini aktive eder. Oturarak veya ayakta uygulanabilir.",
                            IsActive = true,
                            MovementName = "Dumbbell Curl",
                            MuscleGroup = "Biceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000040003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kablo makinesiyle yapılan bu curl çeşidi, hareket boyunca sabit gerilim sağlar. Serbest ağırlıklara kıyasla pik kasılma noktasında daha fazla direnç sunar ve kasın tam kasılmasını zorlar.",
                            IsActive = true,
                            MovementName = "Cable Curl",
                            MuscleGroup = "Biceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000040004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vaiz tezgahı üzerinde yapılan bu egzersiz, üst kolun sabitlenmesiyle biceps'i izole eder ve momentum kullanımını engeller. Uzun baş liflerini özellikle gerilim altında tutar.",
                            IsActive = true,
                            MovementName = "Preacher Curl",
                            MuscleGroup = "Biceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000050001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Paralel bar veya bench üzerinde vücut ağırlığıyla yapılan bu egzersiz, trisepsin tüm üç başını çalıştırır. Gövde dik tutulduğunda triseps aktivasyonu artar; öne eğilince göğüs daha fazla devreye girer.",
                            IsActive = true,
                            MovementName = "Tricep Dips",
                            MuscleGroup = "Triceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000050002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kablo makinesiyle halat aparatı kullanılarak yapılan bu itme hareketi, trisepsin lateral başını izole eder. Hareketin sonunda halat iki yana açılarak tam kasılma sağlanır.",
                            IsActive = true,
                            MovementName = "Rope Pushdown",
                            MuscleGroup = "Triceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000050003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Düz bankta bar veya dumbbell ile yapılan bu egzersiz, trisepsin uzun başını maksimum gerilimde çalıştırır. Ağırlık alnın üzerine indirilip dirseğin açılmasıyla yukarı itilir.",
                            IsActive = true,
                            MovementName = "Skull Crusher",
                            MuscleGroup = "Triceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000050004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kafanın üzerinde uzatma hareketi olarak bilinen bu egzersiz, trisepsin uzun başını en gergin konumda çalıştırır. Dumbbell veya kablo kullanılarak oturarak ya da ayakta uygulanabilir.",
                            IsActive = true,
                            MovementName = "Overhead Extension",
                            MuscleGroup = "Triceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000060001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ters tutuşla yapılan bu curl çeşidi, ön kol ekstansör kaslarını ve brachioradialis'i hedef alır. Normal curl'e göre daha zorlu olan bu hareket, bilek ve ön kol kuvvetini artırır.",
                            IsActive = true,
                            MovementName = "Barbell Curl (Reverse)",
                            MuscleGroup = "Forearms"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000060002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bileği büküp düzelterek yapılan bu izolasyon hareketi, ön kol fleksör kaslarını doğrudan çalıştırır. Bench veya diz üzerine desteklenerek uygulanır; kavrama gücünü artırmada etkilidir.",
                            IsActive = true,
                            MovementName = "Wrist Curls",
                            MuscleGroup = "Forearms"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000070001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bar arka omuzda taşınarak yapılan bu squat çeşidi, quadriceps, gluteus ve hamstring kaslarını bütünsel olarak çalıştırır. Alt vücut gelişiminin temel bileşik hareketi olup yüksek anabolik etki sağlar.",
                            IsActive = true,
                            MovementName = "Barbell Back Squat",
                            MuscleGroup = "Legs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000070002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bacak presi makinesi üzerinde sırt desteğiyle yapılan bu egzersiz, quadriceps ve gluteus kaslarını güvenli biçimde çalıştırır. Bel rahatsızlığı olanlar için squat'a alternatif olarak sıkça tercih edilir.",
                            IsActive = true,
                            MovementName = "Leg Press",
                            MuscleGroup = "Legs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000070003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Makine üzerinde yapılan bu izolasyon hareketi, quadriceps kasını doğrudan hedef alır. Diz eklemine yönelik kesme kuvveti oluşturduğundan ağırlık seçimine dikkat edilmesi gerekir.",
                            IsActive = true,
                            MovementName = "Leg Extension",
                            MuscleGroup = "Legs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000070004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yatay veya oturur pozisyonda makine üzerinde yapılan bu egzersiz, arka uyluk kaslarını izole eder. Diz bükülerek topuk kalçaya yaklaştırılır; hamstring gelişiminin temel hareketidir.",
                            IsActive = true,
                            MovementName = "Hamstring Curl",
                            MuscleGroup = "Legs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000070005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Smith makinesi rayları üzerinde yapılan bu squat çeşidi, denge bileşenini ortadan kaldırarak bacak kaslarına odaklanmayı sağlar. Farklı ayak pozisyonlarıyla farklı kas grupları vurgulanabilir.",
                            IsActive = true,
                            MovementName = "Smith Machine Squat",
                            MuscleGroup = "Legs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000070006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "45 derecelik makine üzerinde yapılan bu squat varyasyonu, quadriceps kaslarını ön plana çıkarır. Sırt bölgesi makine tarafından desteklendiğinden bel üzerindeki yük minimuma iner.",
                            IsActive = true,
                            MovementName = "Hack Squat",
                            MuscleGroup = "Legs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000070007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kızak üzerinde yük iterek yapılan bu fonksiyonel güç egzersizi, tüm alt vücut kaslarını explosive biçimde çalıştırır. Güç, dayanıklılık ve kardiyovasküler kapasiteyi aynı anda geliştirir.",
                            IsActive = true,
                            MovementName = "Leg Sled",
                            MuscleGroup = "Legs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000080001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bar ön omuzda taşınarak yapılan bu squat çeşidi, arka squat'a kıyasla quadriceps kaslarını daha fazla aktive eder. Gövdenin dik tutulması gerektiğinden esneklik ve mobilite açısından zorlu bir harekettir.",
                            IsActive = true,
                            MovementName = "Front Squat",
                            MuscleGroup = "Quadriceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000080002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Topuklar yerden kaldırılarak gövde geriye yatırılan bu egzersiz, quadriceps kaslarını tam açıklıkta izole eder. Diz eklemine olan yük nedeniyle ağırlıksız ya da çok hafif ağırlıkla başlanmalıdır.",
                            IsActive = true,
                            MovementName = "Sissy Squat",
                            MuscleGroup = "Quadriceps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000090001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diz hafifçe bükülü tutularak öne doğru eğilme ve düzelme şeklinde yapılan bu hareket, hamstring ve gluteus kaslarını tam aralıkta çalıştırır. Arka zincir gelişimi için en etkili hareketlerden biridir.",
                            IsActive = true,
                            MovementName = "Romanian Deadlift",
                            MuscleGroup = "Hamstrings"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000090002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bar arka omuzda taşınarak kalçadan öne eğilip düzelme şeklinde yapılan bu egzersiz, hamstring, gluteus ve alt sırt kaslarını birlikte çalıştırır. Düşük ağırlıkla kontrollü yapılması önerilir.",
                            IsActive = true,
                            MovementName = "Good Morning",
                            MuscleGroup = "Hamstrings"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000100001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sırt bench'e yaslanarak barın kalça üzerine yerleştirilmesiyle yapılan bu hareket, gluteus maximus kasını maksimum kasılmada çalıştırır. Kalça yükseltme hareketi olarak bilinen en etkili glute egzersizleri arasındadır.",
                            IsActive = true,
                            MovementName = "Hip Thrust",
                            MuscleGroup = "Glutes"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000100002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Arka ayak bench üzerinde desteklenirken ön ayakla yapılan bu tek bacak squat varyasyonu, gluteus ve quadriceps kaslarını dengeli biçimde çalıştırır. Kas dengesizliklerini gidermeye yardımcı olur.",
                            IsActive = true,
                            MovementName = "Bulgarian Split Squat",
                            MuscleGroup = "Glutes"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000100003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bacak presinde ayakların platformun üst kısmına yerleştirilmesiyle gluteus kaslarının aktivasyonu artırılır. Kalça açısı değiştirilerek hamstring ve gluteus'un farklı lifleri vurgulanır.",
                            IsActive = true,
                            MovementName = "Glute-Focused Leg Press",
                            MuscleGroup = "Glutes"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000110001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ayak uçlarına yükselerek yapılan bu egzersiz, gastrocnemius ve soleus kaslarını çalıştırır. Topuk aşağıda serbest bırakılarak tam aralıkta hareket edilmesi kas gelişimi için kritik öneme sahiptir.",
                            IsActive = true,
                            MovementName = "Calf Raise",
                            MuscleGroup = "Calves"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000110002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Makine üzerinde omuzlardan yüklenerek yapılan bu baldır egzersizi, gastrocnemius kasını izole eder. Kontrollü negatif fazı sayesinde eksantrik stimülasyon yüksektir.",
                            IsActive = true,
                            MovementName = "Machine Calf Raise",
                            MuscleGroup = "Calves"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000120001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kablo makinesi önünde diz üstü pozisyonda yapılan bu karın egzersizi, rectus abdominis'i yoğun biçimde çalıştırır. Ayarlanabilir ağırlık sayesinde kas gelişimine uygun direnç kolayca belirlenir.",
                            IsActive = true,
                            MovementName = "Cable Crunch",
                            MuscleGroup = "Abs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000120002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Karın kası makinesi üzerinde yapılan bu izolasyon hareketi, rectus abdominis kasını destekli ve kontrollü biçimde çalıştırır. Başlangıç seviyeleri için güvenli ve etkili bir karın egzersizidir.",
                            IsActive = true,
                            MovementName = "Machine Crunch",
                            MuscleGroup = "Abs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000120003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Karın tekeri ile yapılan bu ileri düzey egzersiz, rectus abdominis ve transversus abdominis kaslarını yüksek gerilimde çalıştırır. Gövde stabilitesi ve karın kası kuvveti için son derece etkilidir.",
                            IsActive = true,
                            MovementName = "Ab Wheel Rollout",
                            MuscleGroup = "Abs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000130001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kablo makinesiyle diyagonal bir hareket yolunda gerçekleştirilen bu egzersiz, iç ve dış oblik kasları döndürme hareketi sırasında aktive eder. Rotasyon kuvveti ve gövde stabilitesi için kritik bir harekettir.",
                            IsActive = true,
                            MovementName = "Cable Woodchop",
                            MuscleGroup = "Obliques"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000130002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Landmine aparatına takılı barın iki elle tutularak yanlara döndürülmesiyle yapılan bu hareket, oblik kasları ve rotator core kaslarını işlevsel biçimde çalıştırır. Sporsal performans gelişimi için değerlidir.",
                            IsActive = true,
                            MovementName = "Landmine Rotation",
                            MuscleGroup = "Obliques"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000140001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yerden bar kaldırma olarak bilinen bu bileşik egzersiz, alt sırt, gluteus, hamstring ve quadriceps kaslarını eş zamanlı çalıştırır. Vücuttaki en fazla kas kütlesini aktive eden hareketlerden biri olup anabolik etkisi yüksektir.",
                            IsActive = true,
                            MovementName = "Deadlift",
                            MuscleGroup = "LowerBack"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000140002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hiperextension tezgahında gövde aşağı sarkıtılıp kaldırılarak yapılan bu hareket, erector spinae ve alt sırt kaslarını güçlendirir. Bel sağlığını desteklemek ve deadlift performansını artırmak için etkilidir.",
                            IsActive = true,
                            MovementName = "Hyperextension",
                            MuscleGroup = "LowerBack"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000150001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bar tutularak omuzların yukarı kaldırılıp bırakılması şeklinde yapılan bu egzersiz, üst trapez kasını izole eder. Ağır ağırlıklarla yapılabilen bu hareket, omuz ve boyun bölgesinin kalın görünümünü destekler.",
                            IsActive = true,
                            MovementName = "Barbell Shrugs",
                            MuscleGroup = "Traps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000150002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Her iki elde dumbbell tutularak yapılan bu omuz kaldırma hareketi, trapez kasını dengeli biçimde çalıştırır. Dumbbell'ların vücudun yanında serbestçe asılı kalması, hareket açısını artırır.",
                            IsActive = true,
                            MovementName = "Dumbbell Shrugs",
                            MuscleGroup = "Traps"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000160001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Geniş tutuşla kablo üzerinden yapılan bu çekiş, latissimus dorsi kasını en geniş açıyla aktive eder. Bar göğüse indirilirken dirsekler yanlara doğru açılır ve sırt kaslarının tam kasılması hissedilir.",
                            IsActive = true,
                            MovementName = "Wide Grip Lat Pulldown",
                            MuscleGroup = "LatissimusDorsi"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000160002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ters tutuşla yapılan bu lat pulldown çeşidi, latissimus dorsi'nin yanı sıra biceps kasını da yoğun biçimde aktive eder. Alt lat liflerini hedef alması bakımından geniş tutuşa tamamlayıcı niteliktedir.",
                            IsActive = true,
                            MovementName = "Underhand Lat Pulldown",
                            MuscleGroup = "LatissimusDorsi"
                        });
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.FitnessGoalItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_FitnessGoals_IsActive");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_FitnessGoals_Name");

                    b.ToTable("FitnessGoals", (string)null);
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Packages_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Packages_Name");

                    b.ToTable("Packages", (string)null);
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Payments_CreatedAt");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("IX_Payments_PackageId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Payments_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Payments_UserId");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Payments_UserId_IdempotencyKey")
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.TrainingProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletedWeeks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DailyProgramJson")
                        .HasColumnType("json");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Difficulty")
                        .HasColumnType("text");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CoachId")
                        .HasDatabaseName("IX_TrainingPrograms_CoachId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_TrainingPrograms_IsActive");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_TrainingPrograms_UserId");

                    b.ToTable("TrainingPrograms", (string)null);
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("FitnessGoalId")
                        .HasColumnType("uuid");

                    b.Property<string>("FitnessLevel")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<decimal?>("Height")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsCompletedProfile")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("FitnessGoalId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Users_IsActive");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.UserPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MeasurementsJson")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ViewType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserPhotos_UserId");

                    b.HasIndex("ViewType")
                        .HasDatabaseName("IX_UserPhotos_ViewType");

                    b.ToTable("UserPhotos", (string)null);
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.WaitingUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsWaitingForAssignment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsWaitingForAssignment")
                        .HasDatabaseName("IX_WaitingUsers_IsWaitingForAssignment");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_WaitingUsers_UserId");

                    b.ToTable("WaitingUsers", (string)null);
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.CoachUser", b =>
                {
                    b.HasOne("ChangeMind.Domain.Entities.Coach", "Coach")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChangeMind.Domain.Entities.User", "User")
                        .WithMany("CoachRelationships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.Payment", b =>
                {
                    b.HasOne("ChangeMind.Domain.Entities.Package", "Package")
                        .WithMany("Payments")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChangeMind.Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.TrainingProgram", b =>
                {
                    b.HasOne("ChangeMind.Domain.Entities.Coach", "CreatedBy")
                        .WithMany("CreatedPrograms")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChangeMind.Domain.Entities.User", "AssignedTo")
                        .WithMany("AssignedPrograms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.User", b =>
                {
                    b.HasOne("ChangeMind.Domain.Entities.FitnessGoalItem", null)
                        .WithMany()
                        .HasForeignKey("FitnessGoalId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.UserPhoto", b =>
                {
                    b.HasOne("ChangeMind.Domain.Entities.User", "User")
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.WaitingUser", b =>
                {
                    b.HasOne("ChangeMind.Domain.Entities.User", "User")
                        .WithOne("WaitingUserRecord")
                        .HasForeignKey("ChangeMind.Domain.Entities.WaitingUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.Coach", b =>
                {
                    b.Navigation("AssignedUsers");

                    b.Navigation("CreatedPrograms");
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.Package", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ChangeMind.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedPrograms");

                    b.Navigation("CoachRelationships");

                    b.Navigation("Payments");

                    b.Navigation("Photos");

                    b.Navigation("WaitingUserRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
